### PR TITLE
Prettier printing for cats types

### PR DESCRIPTION
**Pull request by dialelo**

### CODE REVIEW

**Comment by yurrriq** [comment]
:+1: I have a fork with some printing tweaks too, but this looks cleaner. I'll check later today when I'm back to my keyboard. Maybe there are some bits worth merging in.

**Comment by dialelo** [comment]
Awesome, looking forward to add your improvements!

**Comment by dialelo** [comment]
@yurrriq I've added you as a collaborator in cats, feel free to push to this branch!

**Comment by yurrriq** [comment]
:sunglasses: Thanks. Will do, if appropriate.

**Comment by yurrriq** [comment]
Ok so I sort of merged by code with yours and the main difference was my generic "to string" function, which I've now called `#'cats.core/str`. I pushed a new branch, [make-printable], since this might not be everyone's favorite approach.


Here's a WIP macro:
```clojure
;; EB: I'm not sure where this should live.
#?(:clj
   (defmacro make-printable
     "TODO: write docstring"
     [klass]
     #?(:clj  `(defmethod print-method ~klass
                 [~'mv# ^java.io.Writer ~'writer#]
                 (.write ~'writer# (str ~'mv#)))
        :cljs `(extend-type ~klass
                 IPrintWithWriter
                 (-pr-writer [~'mv ~'writer _]
                   (-write ~'writer (str ~'mv)))))))
```

that allows you to write code like:

```clojure
(cats.core/make-printable Just)
(cats.core/make-printable Nothing)
(cats.core/make-printable Left)
(cats.core/make-printable Right)
;; etc
```

and reduce the now identical boilerplate code.

The macro doesn't work in CLJS and I'm still pretty green on that front.



[make-printable]: https://github.com/funcool/cats/tree/make-printable

**Comment by yurrriq** [comment]
Here's the [diff] for convenience.

[diff]: https://github.com/funcool/cats/compare/printing...make-printable

**Comment by niwinz** [comment]
Hi @yurrriq 

Thanks.

I really like the make-printable macro approach in general. But the current PR approach is not so good, because I think  (and you have said) it not works well with clojurescript. In fact the function you have been pushed into the core is analogous to cljs IPrintWithWritter protocol. 

In summary, I'm not sure about `cats.core/str` function but I like the macro approach, so, this afternoon I'll find time for it and take the code of both and combine it into a unified approach.

**Comment by yurrriq** [comment]
Sounds good, @niwinz! I wasn't sure if you'd be into the macro approach, but I tend to reach for abstractions whenever I have to write something identical more than three times.

Maybe we could take it even further and make an analog to Haskell's `deriving`.

Something like:

```clojure
(derive Just Show Eq)
```

**Comment by yurrriq** [comment]
The `str` in the macro is `#'cats.core/str`, by the way.

**Comment by niwinz** [comment]
I just pushed a mixed solution between the initial @dialelo purposed and the @yurrriq idea.

Having a generic str function makes it less personalizable for some types that want show different kind of values so the protocol approach still maters here. So I have defined `Printable` protocol that acts like a platform independent way to obtain a object representation; and later a function `make-printable` that choices the platform way to make a type printable and just invoke the `-repr` function of the `Printable` protocol.

**Comment by dialelo** [comment]
Great work combining both changes, I like this approach. Thanks @niwinz and @yurriq, I'm merging it!

**Comment by yurrriq** [comment]
Nice! I like this.

**Pull request merged**
