### PR TITLE
Macro for lifting a function to an applicative

### PR DESCRIPTION
**Pull request by dialelo**
~~Still not ready, need to finish #77 first.~~ I'll tackle #77 later.

### CODE REVIEW

**Comment by dialelo** [comment]
@niwinz @yurrriq I think we can add this before #77, take a look please.

**Comment by niwinz** [comment]
It is ok for me ;)

**Comment by yurrriq** [comment]
LGTM

**Comment by dialelo** [comment]
I'll rebase and merge then!

**Pull request merged**
