### PR TITLE
Reader conditionals

### PR DESCRIPTION
**Pull request by dialelo**

### CODE REVIEW

**Comment by niwinz** [comment]
Great work!

I'm not clearly familiar with reader conditionals and cljc extension but macros, can them to be declared in clj extension without constant abuse of conditionals on cljc files?

The syntax is slightly ugly in some cases :(

But in any case thanks for the work, I'll review it and experiment something and merge!
Also I have plans for pass this to boot-clj  ;) seems a good moment for it.

**Comment by dialelo** [comment]
> I'm not clearly familiar with reader conditionals and cljc extension but macros, can them to be declared in clj extension without constant abuse of conditionals on cljc files?

Yes, that should be definitely possible. Are you suggesting something like creating namespaces for putting the macros? I think it may help clean the code.

> The syntax is slightly ugly in some cases :(

Definitely, I'm not sure wether my approach here is the most beautiful, it was mainly to unlock the first effort required to port to reader conditionals. 

> But in any case thanks for the work, I'll review it and experiment something and merge!
Also I have plans for pass this to boot-clj ;) seems a good moment for it.

Cool, feel free to add your changes to this branch!

**Comment by niwinz** [comment]
I postpone the boot-clj migration because I'm not petty convinced with my current experiments with boot-clj workflow for libraries like cats :S

**Comment by dialelo** [comment]
Okey, looking forward to hear about the reasons. Thanks!

**Pull request merged**
