### PR TITLE
Bifunctor

### PR DESCRIPTION
**Pull request by yurrriq**
Add Bifunctor per #123

- Needs review and better docstrings.
- fe4551cfb58163405b93d823e28f86df2a898edf is particularly contentious.

### CODE REVIEW

**Comment by dialelo** [comment]
Thanks @yurrriq, looks good! A couple comments:

- Could we only define the `bimap` operation on the protocol? seems that `first` and `second` can be derived from it.
- About the names `first` and `second`: I usually don't mind overriding Clojure core names for the API when the functions are semantically similar but in this case I'd choose different names, they are too different to the built-in `first` and `second`. Thoughts?

**Comment by yurrriq** [comment]
We could definitely define only `bimap` and the derive `first` and `second`. I had a version going with a default implementation (`(extend-type Object Bifunctor ...)`) that did just that but had some trouble passing the tests. It could be worth looking into again as I think the issue was with `cats.monad.either/branch{-left,-right,}` being defined in terms of `first` and `second`, which is no longer the case.

I, too, don't like these particular `clojure.core` overrides... [Swiftz](https://github.com/typelift/Swiftz) uses `leftMap` and `rightMap`, so maybe `{left,right}-map` or `{first,second}-map`.. I think of those two I prefer `{first,second}-map`. What do you think?

**Comment by dialelo** [comment]
> We could definitely define only bimap and the derive first and second.

Yes, only in `cats.core`. I think the current implementation is all right, delegating to `bimap` using `identity` in one of the two fns.

> I, too, don't like these particular clojure.core overrides... Swiftz uses leftMap and rightMap, so maybe {left,right}-map or {first,second}-map.. I think of those two I prefer {first,second}-map. What do you think?

I think I'd go with `{left,right}-map` but don't have strong arguments. Also, Haskell uses `first` and `second`. Any preference @niwinz ?

**Comment by niwinz** [comment]
I prefer the {left,right}-map, the first and second leaves to confusion with the core functions and the concept of first and second is related to collections not funcion application.

**Comment by niwinz** [comment]
And +1 to define {left,right}-map in terms of -bimap leaving BiFunctor protocol with one unique function.

**Comment by yurrriq** [comment]
:+1: I'm cool with with that. I should be able I update this PR later today.

**Comment by yurrriq** [comment]
I've made the proposed changes and added some (better?) docstrings and examples. This should be good to go now.

**Comment by dialelo** [comment]
Excellent work, thanks a lot @yurrriq!

Now on to add the protocol implementation in funcool/promesa, and I'm going to use it in funcool/muse too to clean up some code. This is a great addition to cats.

**Comment by yurrriq** [comment]
:tada: We did it!

**Pull request merged**
