### PR TITLE
Implement Printable for every Context

### PR DESCRIPTION
**Pull request by yurrriq**

### CODE REVIEW

**Comment by niwinz** [comment]
Implementing the printable for builtin context will not overwrite the default clojure print methods for builtins? Would be not desirable that this happens... the rest is fine, thanks!

**Comment by yurrriq** [comment]
Ah, I'm not sure. My intention was to have the `context` vars themselves be printable. I'll double check it doesn't override the builtin behaviour.

**Comment by niwinz** [comment]
I'm completely wrong. Do like my last comment does not exists :P. It is fine! So feel free to merge.

**Comment by yurrriq** [comment]
Great! I was gonna say I didn't notice anything funny in my REPL earlier.

**Comment by yurrriq** [comment]
Looks like I need to merge in master first.

**Comment by niwinz** [comment]
No, you need fetch master and rebase it ;)

**Pull request merged**
