### PR TITLE
Patch cljs tests

### PR DESCRIPTION
**Pull request by yurrriq**
Subsumes #157.

```
ERROR in (set-semigroup) (:)
Uncaught exception, not in assertion.
expected: nil
  actual: #object[RangeError RangeError: Maximum call stack size exceeded]
```
See [failing test output](https://travis-ci.org/funcool/cats/jobs/112738234#L464).

### CODE REVIEW

**Comment by yurrriq** [comment]
@sfnelson et al., feel free to make a PR against [`patch-cljs-tests`](https://github.com/funcool/cats/tree/patch-cljs-tests) with a fix for the call stack size error.

**Comment by sfnelson** [comment]
I think the call stack size error is unrelated to the other changes. It occurred in a different function for me while I was running tests earlier today.

**Comment by yurrriq** [comment]
The failure seems rather arbitrary and, as you say, unrelated to these changes. I was able to restart the build and turn everything green.

**Comment by sfnelson** [comment]
I had to leave the tests running for 10 minutes before it occurred for me locally. I think it depends on the seed given to quick-check, which unfortunately isn't printed when tests fail.

**Pull request merged**
