### PR TITLE
Foldable

### PR DESCRIPTION
**Pull request by niwinz**
Not ready.

@dialelo let me know you thoughts about this

### CODE REVIEW

**Comment by dialelo** [comment]
Looks good so far, do you have a roadmap for the whole functionality? We should implement Foldable for Maybe, Either and Validation.

**Comment by niwinz** [comment]
@dialelo please review the maybe/either/validation foldable implementation, I'm not pretty sure about it correctness.

**Comment by dialelo** [comment]
I believe they are correct, must return the seed in Nothing/Left/Fail cases. 

Using `pure` and `return` in the reducing functions only makes sense for Foldables like Maybe/Either/Validation, which have only one value. In Foldables with more than one value like vector you won't be using `pure` since next accumulator would be wrapped in foldable type.

**Comment by niwinz** [comment]
I have reverted the foldm implementation because it was wrong. The correct implementation I think can only be implemented using macros (I'm not pretty sure about it but it seems). I need more research on it and I want do some other improvements to code before implement it.

So this branch is already ready to merge with basic foldable documentation and basic foldable implementation.

**Comment by dialelo** [comment]
I'm going to reword the documentation a bit and add `Foldable` built-in instances to the table in the docs, will merge afterwards. Great work!

**Pull request merged**
