### PR TITLE
Utility functions

### PR DESCRIPTION
**Pull request by dialelo**
Not ready for merge, opening for feedback on the chosen function names. I also noticed that we're missing a continuation monad transformer but that is out of the scope of this PR, I'll work on it in the near future.

### CODE REVIEW

**Comment by dialelo** [comment]
@yurrriq thanks! I'm gonna resume working on this PR and we can cut a release after merging it.

**Comment by dialelo** [comment]
@niwibe I think we can merge this and make the rest of the changes in different PRs, review and merge if you think it's OK.

**Comment by niwibe** [comment]
It is ok for me! Great work!

**Comment by yurrriq** [comment]
:+1:

**Pull request merged**
