### PR TITLE
added try-either which is a sugar macro

### PR DESCRIPTION
**Pull request by shmish111**
for turning a try catch block into an either

### CODE REVIEW

**Comment by dialelo** [comment]
Excellent, a minor comment though: your git configuration's email doesn't match your GitHub username's email and hence it doesn't link the commits to your username. 

If you want to fix it you can change your git configuration, redo the commit and `push -f`. On the contrary, if you are OK with that, we can merge it right away. 

Thanks a lot for your time!

**Comment by dialelo** [comment]
I forgot to mention that macros need to be defined in clojure, so you need to wrap the macro definition in a reader conditional. See the examples in `cats.core`

**Comment by shmish111** [comment]
Damn, hadn't realised it was set to an old work email! Thanks. I've updated the PR.

**Comment by dialelo** [comment]
Excellent, thanks for your time :+1:

**Comment by dialelo** [comment]
Just pushed `1.3.0-SNAPSHOT` to Clojars, it includes your changes. Let us know if you encounter any problems!

**Pull request merged**
