### PR TITLE
Traversable

### PR DESCRIPTION
**Pull request by dialelo**
- [x] Rebase
- [x] Documentation for Traversable
- [x] Lazy sequence traversable implementation
- [x] Pair functor implementation
- [x] Pair foldable implementation
- [x] Pair traversable implementation

### CODE REVIEW

**Comment by niwinz** [comment]
That is the state of this?

Seems that it needs some doc :P

**Comment by dialelo** [comment]
Here's a checklist:
- [ ] Rebase
- [ ] Documentation for Traversable
- [ ] Lazy sequence traversable implementation
- [ ] Pair traversable implementation

**Comment by dialelo** [comment]
@niwinz take a look :eyes:

**Comment by niwinz** [comment]
Great work!

**Pull request merged**
