### PR TITLE
Split lens and traversals

### PR DESCRIPTION
**Pull request by niwinz**
I think that them both has enough identity for have a separated namespace for each one, but I need some feedback for the final decision because them are similar things but mostly used separatelly and for different things.

### CODE REVIEW

**Comment by niwinz** [comment]
@dialelo @yurrriq feedback?

**Comment by niwinz** [comment]
The tests fails because clojars seems has network problems :s 
All tests passes on local.

**Comment by dialelo** [comment]
:+1:, one minor nitpick though: i'd call the namespace cats.labs.traversal for consistency with the singular cats.labs.lens

**Comment by yurrriq** [comment]
:+1: for singular traversal. I'm excited to give this a proper read through later today.

**Comment by niwinz** [comment]
Fixed ns naming! Thanks!

**Comment by yurrriq** [comment]
:+1: to this

**Comment by dialelo** [comment]
:shipit:

**Pull request merged**
