### PR TITLE
improved try-either function

### PR DESCRIPTION
**Pull request by shmish111**
previously it would only take a single form as the body, now it returns the last item in the body as a right, as is normal

### CODE REVIEW

**Comment by shmish111** [comment]
I can't understand what conflicts this branch has, I have updated latest upstream locally with no conflicts :(

**Comment by dialelo** [comment]
We can use `do` instead.

```clojure
(defmacro try-either [body]
  `(try (right (do ~@body)) (catch Exception e# (left e#)))
```

**Comment by dialelo** [comment]
It seems there are still some merge conflicts, I can't merge this from the web interface.

**Comment by shmish111** [comment]
Fixed merge issue. Also, sorry about not spotting the need to separate js and java errors, I'm new to cljc so this stuff escaped my thought process.

**Comment by shmish111** [comment]
@dialelo this doesn't appear to be my PR that is breaking the tests...

**Comment by yurrriq** [comment]
@shmish111: Agreed. See #160.

**Comment by dialelo** [comment]
Thanks a lot for your time and sorry for my delay.

**Pull request merged**
