### PR TITLE
test.check integration & property-based testing

### PR DESCRIPTION
**Pull request by dialelo**
- [x] Generator monad
- [x] Property generators for laws
- [x] Generative testing of laws for every type in cats core
- [x] Documentation

### CODE REVIEW

**Comment by dialelo** [comment]
@niwinz @yurrriq I consider this ready, please take a look!

**Comment by yurrriq** [comment]
Looks good! I made a few tweaks at #127 and #128

**Comment by niwinz** [comment]
I'll wait until @yurrriq changes are included in this pr.

**Comment by dialelo** [comment]
Changes included, thanks @yurrriq!

**Comment by niwinz** [comment]
Seems that pr has conflicts with master :P

**Comment by dialelo** [comment]
Rebased!

**Comment by yurrriq** [comment]
@niwinz, @dialelo. Most of my changes were cosmetic, but you should double check the `gen/set` part and also I changed a few curried anonymous functions to `constantly`.

**Comment by dialelo** [comment]
Looks good to me!

**Pull request merged**
